package com.hanx.sunnyweathercompose.logic.model

import com.hanx.sunnyweathercompose.R

class Sky(val info: String, val iconResId: Int, val bgResId: Int = R.drawable.bg_clear_day)

fun getSky(iconId: String) =
    skyMap[iconId] ?: Sky("未知", R.drawable.ic_skycon_999_fill, R.drawable.bg_clear_day)

private val skyMap = mapOf(
    "100" to Sky("晴", R.drawable.ic_skycon_100_fill, R.drawable.bg_clear_day),
    "101" to Sky("多云", R.drawable.ic_skycon_101_fill, R.drawable.bg_partly_cloudy_day),
    "102" to Sky("少云", R.drawable.ic_skycon_102_fill, R.drawable.bg_partly_cloudy_day),
    "103" to Sky("晴间多云", R.drawable.ic_skycon_103_fill, R.drawable.bg_partly_cloudy_day),
    "104" to Sky("阴", R.drawable.ic_skycon_104_fill, R.drawable.bg_cloudy),
    "150" to Sky("晴", R.drawable.ic_skycon_150_fill, R.drawable.bg_clear_night),
    "151" to Sky("多云", R.drawable.ic_skycon_151_fill, R.drawable.bg_partly_cloudy_night),
    "152" to Sky("少云", R.drawable.ic_skycon_152_fill, R.drawable.bg_partly_cloudy_night),
    "153" to Sky("晴间多云", R.drawable.ic_skycon_153_fill, R.drawable.bg_partly_cloudy_night),
    "300" to Sky("阵雨", R.drawable.ic_skycon_300_fill, R.drawable.bg_cloudy),
    "301" to Sky("强阵雨", R.drawable.ic_skycon_301_fill, R.drawable.bg_rain),
    "302" to Sky("雷阵雨", R.drawable.ic_skycon_302_fill, R.drawable.bg_rain),
    "303" to Sky("强雷阵雨", R.drawable.ic_skycon_303_fill, R.drawable.bg_rain),
    "304" to Sky("雷阵雨伴有冰雹", R.drawable.ic_skycon_304_fill, R.drawable.bg_rain),
    "305" to Sky("小雨", R.drawable.ic_skycon_305_fill, R.drawable.bg_rain),
    "306" to Sky("中雨", R.drawable.ic_skycon_306_fill, R.drawable.bg_rain),
    "307" to Sky("大雨", R.drawable.ic_skycon_307_fill, R.drawable.bg_rain),
    "308" to Sky("极端降雨", R.drawable.ic_skycon_308_fill, R.drawable.bg_rain),
    "309" to Sky("毛毛雨/细雨", R.drawable.ic_skycon_309_fill, R.drawable.bg_rain),
    "310" to Sky("暴雨", R.drawable.ic_skycon_310_fill, R.drawable.bg_rain),
    "311" to Sky("大暴雨", R.drawable.ic_skycon_311_fill, R.drawable.bg_rain),
    "312" to Sky("特大暴雨", R.drawable.ic_skycon_312_fill, R.drawable.bg_rain),
    "313" to Sky("冻雨", R.drawable.ic_skycon_313_fill, R.drawable.bg_rain),
    "314" to Sky("小到中雨", R.drawable.ic_skycon_314_fill, R.drawable.bg_rain),
    "315" to Sky("中到大雨", R.drawable.ic_skycon_315_fill, R.drawable.bg_rain),
    "316" to Sky("大到暴雨", R.drawable.ic_skycon_316_fill, R.drawable.bg_rain),
    "317" to Sky("暴雨到大暴雨", R.drawable.ic_skycon_317_fill, R.drawable.bg_rain),
    "318" to Sky("大暴雨到特大暴雨", R.drawable.ic_skycon_318_fill, R.drawable.bg_rain),
    "350" to Sky("阵雨", R.drawable.ic_skycon_350_fill, R.drawable.bg_rain),
    "351" to Sky("强阵雨", R.drawable.ic_skycon_351_fill, R.drawable.bg_rain),
    "399" to Sky("雨", R.drawable.ic_skycon_399_fill, R.drawable.bg_rain),
    "400" to Sky("小雪", R.drawable.ic_skycon_400_fill, R.drawable.bg_snow),
    "401" to Sky("中雪", R.drawable.ic_skycon_401_fill, R.drawable.bg_snow),
    "402" to Sky("大雪", R.drawable.ic_skycon_402_fill, R.drawable.bg_snow),
    "403" to Sky("暴雪", R.drawable.ic_skycon_403_fill, R.drawable.bg_snow),
    "404" to Sky("雨夹雪", R.drawable.ic_skycon_404_fill, R.drawable.bg_rain),
    "405" to Sky("雨雪天气", R.drawable.ic_skycon_405_fill, R.drawable.bg_snow),
    "406" to Sky("阵雨夹雪", R.drawable.ic_skycon_406_fill, R.drawable.bg_rain),
    "407" to Sky("阵雪", R.drawable.ic_skycon_407_fill, R.drawable.bg_snow),
    "408" to Sky("小到中雪", R.drawable.ic_skycon_408_fill, R.drawable.bg_snow),
    "409" to Sky("中到大雪", R.drawable.ic_skycon_409_fill, R.drawable.bg_snow),
    "410" to Sky("大到暴雪", R.drawable.ic_skycon_410_fill, R.drawable.bg_snow),
    "456" to Sky("阵雨夹雪", R.drawable.ic_skycon_456_fill, R.drawable.bg_rain),
    "457" to Sky("阵雪", R.drawable.ic_skycon_457_fill, R.drawable.bg_snow),
    "499" to Sky("雪", R.drawable.ic_skycon_499_fill, R.drawable.bg_snow),
    "500" to Sky("薄雾", R.drawable.ic_skycon_500_fill, R.drawable.bg_fog),
    "501" to Sky("雾", R.drawable.ic_skycon_501_fill, R.drawable.bg_fog),
    "502" to Sky("霾", R.drawable.ic_skycon_502_fill, R.drawable.bg_fog),
    "503" to Sky("扬沙", R.drawable.ic_skycon_503_fill, R.drawable.bg_fog),
    "504" to Sky("浮尘", R.drawable.ic_skycon_504_fill, R.drawable.bg_fog),
    "507" to Sky("沙尘暴", R.drawable.ic_skycon_507_fill, R.drawable.bg_fog),
    "508" to Sky("强沙尘暴", R.drawable.ic_skycon_508_fill, R.drawable.bg_fog),
    "509" to Sky("浓雾", R.drawable.ic_skycon_509_fill, R.drawable.bg_fog),
    "510" to Sky("强浓雾", R.drawable.ic_skycon_510_fill, R.drawable.bg_fog),
    "511" to Sky("中度霾", R.drawable.ic_skycon_511_fill, R.drawable.bg_fog),
    "512" to Sky("重度霾", R.drawable.ic_skycon_512_fill, R.drawable.bg_fog),
    "513" to Sky("严重霾", R.drawable.ic_skycon_513_fill, R.drawable.bg_fog),
    "514" to Sky("大雾", R.drawable.ic_skycon_514_fill, R.drawable.bg_fog),
    "515" to Sky("特强浓雾", R.drawable.ic_skycon_515_fill, R.drawable.bg_fog),
    "900" to Sky("热", R.drawable.ic_skycon_900_fill, R.drawable.bg_fog),
    "901" to Sky("冷", R.drawable.ic_skycon_901_fill, R.drawable.bg_fog),
    "999" to Sky("未知", R.drawable.ic_skycon_999_fill, R.drawable.bg_clear_day)
)